### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [helloramon/pipeline_setup#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by helloramon** [comment]
![gh_01](https://cloud.githubusercontent.com/assets/10609357/6222351/d6f01580-b606-11e4-9ad2-58001b516a5b.jpg)

I searched through google, but the most common response I found regarding a meta tag for mobile devices was the viewport line I had in. Is there an additional attribute I should be searching for?

Thanks in advance!

**Comment by MarcoMorawec** [comment]
:+1: @helloramon you are spot on and I somehow missed your line of code, since I usually place it below the meta tags.

Great job on communicating that fact the way you did - that's exactly how developers communicate: straight and to the point.

Keep up the great work and close the issue, since it really wasn't one :)

**Comment by helloramon** [comment]
@MarcoMorawec Thank you for looking at my code, and advice on communication! I'm normally not a super direct person (only when I have to be) because I feel at times it can be misconstrued as being rude, especially on the web, and I don't want to step on anyones toes. But I do understand that it's probably the most effective way to get things resolved.
